### PR TITLE
Add SODIMM DDR2

### PR DESCRIPTION
**Pull request by Rosc**
Hi,

I created a DDR2 template in matching style.  There is some demand for this, as it is the format used for the older-style raspberry pi  compute modules, and your repo is one of the only useful results when looking for SODIMM layouts for Kicad

### CODE REVIEW

**Comment by Wallbraker** [comment]
Oh thank you very much! :D And apologies for not merging this sooner. If you have the time and will it would be good if you would do a follow up PR that adds a edge connector as well.

Side note, a bit surprising that I seem to have become the defacto source for these.

**Comment by Rosc** [comment]
No worries, especially during the holiday season. I may be misunderstanding so please feel free to clarify if I'm wrong, but the edge connectors are already in the template.  Depending on your settings, they may be hidden by the front and back mask layers.

**Comment by Wallbraker** [comment]
> No worries, especially during the holiday season. I may be misunderstanding so please feel free to clarify if I'm wrong, but the edge connectors are already in the template. Depending on your settings, they may be hidden by the front and back mask layers.

Ah humm, I have to admit that I don't exactly remember the specifics (and why) but for each SODIMM connector template there is a file in the `SODIMM.pretty` folder. And I noticed that your commit didn't add a file in that folder, now I have to admit I don't remember why I added the `SODIMM.pretty` folder, sorry. :-/

**Comment by Rosc** [comment]
I had to look it up.  It looks like the .pretty files are settings to drop in a design as a custom footprint in another PCB.  It shouldn't be a big deal to add that, so I'll mess around with it this week.

**Pull request merged**
